config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show, :update]
    resources :tomes, only: [:index, :show, :create, :update]
    resources :shelves, only: [:show, :create, :update, :destroy]
    resources :shelvings, only: [:create, :destroy]
    resources :reviews, only: [:index, :create, :update, :destroy]
  end
end

app/views/shared/_description.html.erb
<span class="landing-description">A haven for magical practitioners to rate and review tomes of magical lore.</span>

app/views/shared/_form.html.erb
  <div class="user-form-wrapper">
    <% if flash["errors"] %>
      <div class="alert alert-danger">
          <% flash["errors"].each do |error| %>
            <p><%= error %></p>
          <% end %>
      </div>
    <% end %>
    <form class="user-form" id="<%= id %>" action="<%= url %>" method="post">
      <%= auth_token %>

      <input type="text" class="form-control" required pattern="\w+" name="user[username]" placeholder="PractitionerName" value="<%= @user && @user.username %>">

      <input type="password" class="form-control" required pattern="\S{6,}" onchange="form.vpassword.pattern = this.value;" name="user[password]" placeholder="Password">

      <% if id == "user-form" %>
        <input type="password" name="vpassword" required pattern="\S{6,}" class="form-control" placeholder="Verify Password">
      <% end %>

      <input type="submit" value="<%= submit_value %>" class="btn <%= button_class %> form-control">
    </form>
  </div>

app/views/shared/_landing.html.erb
<div class="login-wrapper">
  <a href="/">
    <img src="/assets/grimoire-logo.png" class="logo" />
  </a>

  <% if !current_user %>
    <div class="session">
      <%= render partial: "shared/description" %>
      <%= render partial: "shared/form", locals: {
        url: "/session",
        submit_value: "Sign In",
        button_class: "btn-primary",
        id: "session-form"
      } %>
      <div class="log-state">
        <%= link_to "Sign In", "#", class: "btn selected sign-in" %>
        <%= link_to "Sign Up", "#", class: "btn inactive sign-up" %>
      </div>
    </div>
    <div class="user">
      <%= render partial: "shared/description" %>
      <%= render partial: "shared/form", locals: {
        url: "/users",
        submit_value: "Sign Up",
        button_class: "btn-success",
        id: "user-form"
      } %>
      <div class="log-state">
        <%= link_to "Sign In", "#", class: "btn inactive sign-in" %>
        <%= link_to "Sign Up", "#", class: "btn selected sign-up" %>
      </div>
    </div>
    <%= link_to 'Speak "Guest" and Enter', '#', class: "btn guest" %>
  <% else %>
    <div class="user-form-wrapper">
      <p>
        You're logged in as: <%= link_to current_user.username, "#", class: :btn %>
      </p>
    </div>
    <div class="log-state">
      <%= link_to "Sign Out", session_url, method: :delete, class: "btn inactive" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  var userButton = $('.sign-up');
  var sessionButton = $('.sign-in');
  var guestButton = $('.guest');

  var inputLength = 0;
  var userEl = $('#session-form input[name="user[username]"]');
  var userInput = "Myrddin";
  var passwordEl = $('#session-form input[name="user[password]"]');
  var passwordInput = "password";

  userButton.click(function () {
    $('.user').css("display", "block");
    $('.session').css("display", "none");
  });

  sessionButton.click(function () {
    $('.session').css("display", "block");
    $('.user').css("display", "none");
  });

  guestButton.click(function () {
    sessionButton.click();
    typeUsername.call(this);
  }.bind(this));

  function typeUsername() {
    userEl.val(userInput.substr(0, inputLength++));
    if(inputLength < userInput.length+1) {
      setTimeout('typeUsername()', 50);
    } else {
      inputLength = 0;
      userInput = '';
      typePassword();
    }
  };

  function typePassword() {
    passwordEl.val(passwordInput.substr(0, inputLength++));
    if(inputLength < passwordInput.length+1) {
      setTimeout('typePassword()', 50);
    } else {
      inputLength = 0;
      passwordInput = '';
      $('#session-form').submit();
    }
  };
</script>